# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches:
      - main
      - continious_integration
  pull_request:
    branches:
      - main
      - continious_integration
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.10
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle install

      - name: Set up database
        run: |
          bin/rails db:setup RAILS_ENV=test
          
      - name: Run Tests
        run: |
          bin/rails test

  